export const SET_SQUARE_D = 'set_square_D'
export const SET_CHESS_D = 'set_chess_d'
export const UPDATE_SELECTED_CHESS_COORDINATE = 'update_selected_chess_coordinate'
export const SET_CURRENT_STEP = 'set_current_step'
export const SET_HISTORY = 'set_history'
export const SET_ABLE_RECEIVE_COORDINATES = 'set_able_receive_coordinates'